config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books
  resources :comments, only: [:create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
      can :update, :all
      can :read, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  #load_and_authorize_resource
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
    def index
        @books = Book.all
        #authorize! :read, @book, :message => "Unable to read Articles."
    end

    def show
        @book = Book.find(params[:id])
        authorize! :read, @book, :message => "Unable to read Articles."
    end

    def new
         @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
          redirect_to @book
        else
          render :new
        end
    end

    def edit
        @book = Book.find(params[:id])
        authorize! :manage, @book, :message => "Unable to read Articles."
    end

    def update
        @book = Book.find(params[:id])
        #authorize! :manage, @book, :message => "Unable to read Articles."
        if @book.update(book_params)
          redirect_to @book
        else
          render :edit
        end
    end


    def destroy
        @book = Book.find(params[:id])
        authorize! :manage, @book, :message => "Unable to read Articles."
        @book.destroy
      
        redirect_to books_path
    end

    private
        def book_params
            params.require(:book).permit(:title, :author, :description, :publication_date, :price)
        end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @name = "Pedro"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
      <div class="card-header font-weight-bold"><%= title %></div>
        <%= form_for @book do |f| %>
        <div class="card-body">
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :author %>
            <%= f.text_field :author, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 4, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :publication_date %>
            <%= f.date_field :publication_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control", step: :any %>
          </div>

        </div>
        <div class="card-footer text-right">
          <%= link_to "Cancelar", books_path, class: "btn btn-default" %>
          <%= f.submit class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
   <%= render "form", title: "Editar Libro" %>

app/views/books/index.html.erb
<div class="books-page">
  <div class="container">
  <% if can? :manage, @books %>
    <div class="text-right"><%= link_to "Agregar Libro", new_book_path, class: "btn btn-primary rounded-0" %></div>
  <% end %>
    <div>Bienvenido <%= current_user.id %> </div>
    <% @books.each do |book| %>
      <div class="book card flex-sm-row align-items-center align-items-sm-start mt-5">
        <div class="card-body">
          <h5 class="card-title">
            <%= book.title %>
            <small><%= book.author %></small>
          </h5>
          <p class="card-text"><%= book.description %></p>
          <%= link_to "Detalles", book, class: "btn btn-primary" %>
          <% if can? :manage, book %>
            <%= link_to "Editar", edit_book_path(book), class: "btn btn-link" %>
            <%= link_to "Eliminar", book, class: "btn btn-link text-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= render "form", title: "Agregar Libro" %>

app/views/books/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, books_path, class: "btn btn-link" %>
    <div>Bienvenido <%= current_user.id %> </div>
    <header class="main">
      <h2><%= @book.title %></h2>
      <div class="author"><%= @book.author %></div>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
      <div class="book-details">
        <p><%= @book.description %></p>
        <dl>
          <dt>Fecha de publicación</dt>
          <dd><%= @book.publication_date %></dd>
          <dt>Precio</dt>
          <dd><%= @book.price %></dd>
        </dl>
        <div class="text-right">
        <% if can? :manage, @books %>
            <%= link_to "Editar", edit_book_path(@book), class: "btn btn-link" %>
            <%= link_to "Eliminar", @book, class: "btn btn-link text-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if signed_in? %>
        <%= link_to "Salir", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Registrarse", new_user_registration_path %>
        <%= link_to "Ingresar", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% 3.times do %>
    <p>Hola Mundo</p>
<% end %>
<h1>Hola <%= @name %></h1>
<h1>Hola <%= params[:name] %></h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>